//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C969Scheduler.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("C969Scheduler.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _12607_close_delete_error_exit_false_icon {
            get {
                object obj = ResourceManager.GetObject("_12607_close_delete_error_exit_false_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1564534_customer_man_user_account_profile_icon {
            get {
                object obj = ResourceManager.GetObject("_1564534_customer_man_user_account_profile_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _23231_delete_icon {
            get {
                object obj = ResourceManager.GetObject("_23231_delete_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _23498_go_next_old_icon {
            get {
                object obj = ResourceManager.GetObject("_23498_go_next_old_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _23499_go_old_previous_icon {
            get {
                object obj = ResourceManager.GetObject("_23499_go_old_previous_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _24350_system_software_update_reload_actualizar_icon {
            get {
                object obj = ResourceManager.GetObject("_24350_system_software_update_reload_actualizar_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _285657_floppy_guardar_save_icon {
            get {
                object obj = ResourceManager.GetObject("_285657_floppy_guardar_save_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3044882_extension_file_spreadsheet_xls_icon {
            get {
                object obj = ResourceManager.GetObject("_3044882_extension_file_spreadsheet_xls_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _34217_close_delete_remove_icon {
            get {
                object obj = ResourceManager.GetObject("_34217_close_delete_remove_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _34237___add_plus_icon {
            get {
                object obj = ResourceManager.GetObject("_34237___add_plus_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _49615_reports_report_documents_icon {
            get {
                object obj = ResourceManager.GetObject("_49615_reports_report_documents_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _532741_appointment_calendar_date_month_planner_icon {
            get {
                object obj = ResourceManager.GetObject("_532741_appointment_calendar_date_month_planner_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _79433_home_icon {
            get {
                object obj = ResourceManager.GetObject("_79433_home_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _8674501_ic_fluent_calendar_today_regular_icon {
            get {
                object obj = ResourceManager.GetObject("_8674501_ic_fluent_calendar_today_regular_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _8674567_ic_fluent_calendar_week_numbers_icon {
            get {
                object obj = ResourceManager.GetObject("_8674567_ic_fluent_calendar_week_numbers_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address 2 cannot be empty. If no Apt., Suite, or Unit number please us &quot;N/A&quot;..
        /// </summary>
        internal static string Address2 {
            get {
                return ResourceManager.GetString("Address2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted..
        /// </summary>
        internal static string AppDeleted {
            get {
                return ResourceManager.GetString("AppDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  has an appointment with .
        /// </summary>
        internal static string AppWith {
            get {
                return ResourceManager.GetString("AppWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you would like to delete this appointment?.
        /// </summary>
        internal static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you would like to delete this address?.
        /// </summary>
        internal static string AreYouSureAddress {
            get {
                return ResourceManager.GetString("AreYouSureAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you would like to delete this city?.
        /// </summary>
        internal static string AreYouSureCity {
            get {
                return ResourceManager.GetString("AreYouSureCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you would like to delete this country?.
        /// </summary>
        internal static string AreYouSureCountry {
            get {
                return ResourceManager.GetString("AreYouSureCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you would like to delete this customer?.
        /// </summary>
        internal static string AreYouSureCustomer {
            get {
                return ResourceManager.GetString("AreYouSureCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  at .
        /// </summary>
        internal static string at {
            get {
                return ResourceManager.GetString("at", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot book in the past..
        /// </summary>
        internal static string CannotBookInPast {
            get {
                return ResourceManager.GetString("CannotBookInPast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t delete a customer that currently has an appointment..
        /// </summary>
        internal static string CannotDelet {
            get {
                return ResourceManager.GetString("CannotDelet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the city from the list..
        /// </summary>
        internal static string CityId {
            get {
                return ResourceManager.GetString("CityId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outside working hours.
        /// </summary>
        internal static string Closed {
            get {
                return ResourceManager.GetString("Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Error! .
        /// </summary>
        internal static string ConnectionError {
            get {
                return ResourceManager.GetString("ConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the country from the list..
        /// </summary>
        internal static string CountryId {
            get {
                return ResourceManager.GetString("CountryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current user:.
        /// </summary>
        internal static string Current {
            get {
                return ResourceManager.GetString("Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer deleted..
        /// </summary>
        internal static string CustomerDeleted {
            get {
                return ResourceManager.GetString("CustomerDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data not found!.
        /// </summary>
        internal static string DataNotFound {
            get {
                return ResourceManager.GetString("DataNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This date and time are taken for this contact. Please specify the time in 24 hour format..
        /// </summary>
        internal static string DateTaken {
            get {
                return ResourceManager.GetString("DateTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete?.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill all required fields..
        /// </summary>
        internal static string Fieldsincomplete {
            get {
                return ResourceManager.GetString("Fieldsincomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect username or password. Please try again..
        /// </summary>
        internal static string LoginError {
            get {
                return ResourceManager.GetString("LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed.
        /// </summary>
        internal static string LoginFail {
            get {
                return ResourceManager.GetString("LoginFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Month.
        /// </summary>
        internal static string NextM {
            get {
                return ResourceManager.GetString("NextM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Week.
        /// </summary>
        internal static string NextW {
            get {
                return ResourceManager.GetString("NextW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an address to update..
        /// </summary>
        internal static string NoAddressSelected {
            get {
                return ResourceManager.GetString("NoAddressSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an appointment to update..
        /// </summary>
        internal static string NoAppointmentSelected {
            get {
                return ResourceManager.GetString("NoAppointmentSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a city to update..
        /// </summary>
        internal static string NoCitySelected {
            get {
                return ResourceManager.GetString("NoCitySelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a country to update..
        /// </summary>
        internal static string NoCountrySelected {
            get {
                return ResourceManager.GetString("NoCountrySelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a customer..
        /// </summary>
        internal static string NoCustomerSelected {
            get {
                return ResourceManager.GetString("NoCustomerSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing Deleted..
        /// </summary>
        internal static string NothingDeleted {
            get {
                return ResourceManager.GetString("NothingDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing Saved..
        /// </summary>
        internal static string NothingSaved {
            get {
                return ResourceManager.GetString("NothingSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a time between 9am and 5pm..
        /// </summary>
        internal static string OutsideHours {
            get {
                return ResourceManager.GetString("OutsideHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Month.
        /// </summary>
        internal static string PrevM {
            get {
                return ResourceManager.GetString("PrevM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Week.
        /// </summary>
        internal static string PrevW {
            get {
                return ResourceManager.GetString("PrevW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved!.
        /// </summary>
        internal static string Saved {
            get {
                return ResourceManager.GetString("Saved", resourceCulture);
            }
        }
    }
}
